### ISSUE TITLE
Issue with multiple endpoints

### ISSUE THREAD

**Issue by patpatpat123** [nlinhvu/rest-client-demo-2024#1]
Hello!

First of all, I just wanted to say thank you for your video series.
I am one of your YouTube fans, if not anything else, please keep the series going.
They are interesting to watch and easy to understand.

My issue:
We looked at the video series, especially
1 multiple RestClient video
2 the SpringBoot security OAuth2 JWT series
3 the SpringBoot Actuator/Micrometer and observability videos

We have a use case, where it needs to combine all the above.

Our use case is as follows, our app needs to talk to a first ServerResourceA, which is protected and needs a token, but from a TokenProviderB.
Then, it needs to get a resource from yet another ServerResouceC, using yet another token from yet another token from TokenProviderD. 
This is 4 servers in total!
This is very important, 4 different endpoints here

In your example, you are saying we need to reuse the restclient since it is thread-safe, avoiding multiple RestClient.create();
```
1. Practice when using RestClient

Noted: RestClient is thread-safe
```
But, we need observability, hence, we cannot just use https://github.com/nlinhvu/rest-client-demo-2024?tab=readme-ov-file#12-create-only-one-instance-for-a-entire-service. 
```
@Configuration
public class WebConfig {

    @Bean
    public RestClient restClient() {
       return RestClient.create();
    }
}
```
We need to use ```RestClient.Builder builder```
Hence, we came up with this code:

```
@RestController
public class GreetingController {

    private final HelloServiceClient helloServiceClient;
    private final HiServiceClient hiServiceClient;

    public GreetingController(HelloServiceClient helloServiceClient, HiServiceClient hiServiceClient) {
        this.helloServiceClient = helloServiceClient;
        this.hiServiceClient = hiServiceClient;
    }

    @GetMapping("/hellohi")
    String hellohi() {
        System.out.println("here");
        return this.helloServiceClient.hello() + this.hiServiceClient.hi();
    }

}
```

```
@Service
public class HelloServiceClient {

    private static final Logger log = LoggerFactory.getLogger(HelloServiceClient.class);

    private final RestClient restClient;

    public HelloServiceClient(RestClient.Builder builder, @Value("${application.url.hello}") String urlHello) {
        this.restClient = builder
                .baseUrl(urlHello)
                .requestInterceptor(
                        (request, body, execution) -> {
                            log.info("Lambda Interceptor: modifying before sending request");
                            ClientHttpResponse response = execution.execute(request, body);
                            log.info("Lambda Interceptor: modifying after receiving response");
                            return response;
                        }
                )
                .build();
    }

    public String hello() {
        return this.restClient.get()
                .uri("/hello")
                .attributes(clientRegistrationId("hello-client"))
                .retrieve()
                .body(String.class);
    }

}
```

```
package vn.cloud.restclientdemo.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import static org.springframework.security.oauth2.client.web.client.RequestAttributeClientRegistrationIdResolver.clientRegistrationId;

@Service
public class HiServiceClient {

    private final RestClient restClient;

    public HiServiceClient(RestClient.Builder builder, @Value("${application.url.hi}") String urlHi) {
        this.restClient = builder
                .baseUrl(urlHi)
                .build();
    }

    public String hi() {
        return this.restClient.get()
                .uri("/hi")
                .attributes(clientRegistrationId("hi-client"))
                .retrieve()
                .body(String.class);
    }

}

```

```
spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          hello-client:
            provider: hello-provider
            client-id: someusername
            client-secret: somepassword
            authorization-grant-type: client_credentials
            scope: resolve
          hi-client:
            provider: hi-provider
            client-id: anotherusername
            client-secret: anotherpassword
            authorization-grant-type: client_credentials
            scope: download
        provider:
          hello-provider:
            token-uri: https://tokenprovider.com/token
          hi-provider:
            token-uri: https://secureservice.com/token

application:
  url:
    hello: https://somecoolcompany.com/api/v1.0/hello
    hi: https://veryawsomeendpoint.com/v2/hi

management:
  tracing:
    sampling:
      probability: '1.0'

```

It is important to observe four different endpoints here.

I am trying this and observed multiple issues
1 ) performance issue:
You mentioned "Noted: RestClient.Builder is prototype bean, 1 new instance of it will be created for each autowiring."
For my use case, since I need observability, I need to use RestClient.Builder builder.
How many RestClient should I create? 1, 2, 4? How many builder should I use? 1, 2, 4?
Could you please suggest what is the correct approach?
Above code is very slow (the four endpoints are very fast, but for some reason, when under high load, the whole system slows down)

2) no observability on the token call:
With above code, I do see the traces for when getting the resources.
But I do not see the trace for the calls to get the token in the first place.
Do you know why?

Here is the attached zip.
Thank you for your time.
